#!/usr/bin/env python3
"""Generate specification compliance tests from upstream KDL fixtures, grouped by category."""

import argparse
import io
import re
import sys
from collections import defaultdict
from pathlib import Path

#  Enforce Python 3.11+ before executing any main logic
if sys.version_info < (3, 11):
    sys.exit("Error: Python 3.11 or higher is required for this script.")

DEFAULT_FIXTURES = Path("tests/fixtures/kdl/test_cases/input")
OUTPUT = Path("package/Compliance.roc")

CATEGORY_PATTERNS = [
    ("Empty / whitespace", [r"empty\.kdl", r"just_newline", r"just_space", r"empty_line_comment"]),
    ("Bare identifiers", [r"bare_ident", r"dash_dash", r"just_node_id"]),
    ("Quoted strings", [r"all_escapes", r"empty_quoted", r"string_arg", r"string_prop", r"quoted"]),
    ("Numbers (decimal)", [r"int_multiple_underscore", r"arg_zero_type", r"integer", r"float"]),
    ("Numbers (hex/octal/binary)", [r"hex\.", r"octal", r"binary"]),
    ("Numbers (keyword)", [r"floating_point_keywords"]),
    ("Booleans & null", [r"boolean", r"true", r"false", r"null"]),
    ("Properties", [r"arg_and_prop", r"prop", r"duplicate"]),
    ("Children blocks", [r"child", r"nested"]),
    ("Multiple nodes", [r"semicolon", r"crlf_between", r"multiple"]),
    ("Type annotations", [r"type", r"annotation"]),
    ("Line comments", [r"line_comment", r"comment_and", r"commented_line"]),
    ("Block comments", [r"block_comment"]),
    ("Slashdash", [
        r"commented_node", r"commented_arg", r"commented_prop",
        r"commented_child", r"commented_children"
    ]),
    ("Line continuations", [r"escline"]),
    ("Multi-line strings", [r"multi_line", r"multiline"]),
    ("Raw strings", [r"raw_string"]),
    ("Unicode whitespace", [r"emoji", r"bare_emoji"]),
    ("Identifier validation", [r"_fail"]),
    ("BOM / version marker", [r"bom"]),
]


def categorise(name: str) -> str:
    """Group input file name by category."""
    for cat, patterns in CATEGORY_PATTERNS:
        for pat in patterns:
            if re.search(pat, name):
                return cat
    return "Other"


def roc_escape(s: str) -> str:
    """Escape special characters so the escape sequences can be written."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def write_header(handle: io.TextIOBase, lines: str | list[str]) -> None:
    """Writes a left-aligned standard framed section header to a file."""
    # If a single string is passed, wrap it in a list to normalise it
    if isinstance(lines, str):
        lines = [lines]

    handle.write("#" * 79 + "\n")
    for line in lines:
        handle.write(f"# {line}\n")
    handle.write("#" * 79 + "\n\n")


def generate(fixtures_path: Path, output_path: Path) -> None:
    """Generate test case data from fixtures."""
    script_name = str(Path(sys.argv[0]))

    categories: dict[str, list[Path]] = defaultdict(list)

    if not fixtures_path.exists():
        sys.exit(f"Error: Fixtures directory '{fixtures_path}' not found.")

    files = sorted(fixtures_path.glob("*.kdl"))
    for f in files:
        cat = categorise(f.name)
        categories[cat].append(f)

    generated_details = [
        f"Generated by {script_name}",
        f"Run: roc test {output_path}"
    ]

    with open(output_path, "w", encoding="utf-8") as out:
        write_header(out, generated_details)
        out.write("module []\n\n")
        out.write("import Kdl exposing [parse]\n\n")

        cat_order = [c for c, _ in CATEGORY_PATTERNS] + ["Other"]
        for cat in cat_order:
            if cat not in categories:
                continue
            write_header(out, cat)
            for f in categories[cat]:
                with open(f, "r", encoding="utf-8") as fixture:
                    content = fixture.read()

                escaped = roc_escape(content)
                is_fail = "_fail" in f.name

                out.write(f'# {f.name}\n')
                out.write("expect\n")
                out.write(f'    result = parse "{escaped}"\n')

                if is_fail:
                    out.write("    Result.is_err result\n")
                else:
                    out.write("    Result.is_ok result\n")
                out.write("\n")

        # Summary: always true (just to have something)
        write_header(out, "Summary")
        out.write("expect\n    Bool.true\n")

    total = len(files)
    cats = len([c for c in cat_order if c in categories])
    print(f"Generated {total} tests across {cats} categories in {OUTPUT}")


def main() -> None:
    """Parse CLI args and run the generator."""
    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        description="Generate specification compliance tests from upstream KDL fixtures."
    )

    #  Optional positional argument: 'nargs="?"' makes it optional
    parser.add_argument(
        "input",
        type=Path,
        nargs="?",
        default=DEFAULT_FIXTURES,
        help=f"Path to input fixtures directory (default: {DEFAULT_FIXTURES})"
    )

    args = parser.parse_args()
    generate(args.input, OUTPUT)


if __name__ == "__main__":
    main()
